Update to v3 dService.

diff --git a/drunner/servicerunner b/drunner/servicerunner
--- a/drunner/servicerunner
+++ b/drunner/servicerunner
@@ -1,13 +1,13 @@
 #!/bin/bash
-                                                                                                                                                          
-#  ad88888ba                                        88                          88888888ba                                                                  
-# d8"     "8b                                       ""                          88      "8b                                                                 
-# Y8,                                                                           88      ,8P                                                                 
-# `Y8aaaaa,     ,adPPYba,  8b,dPPYba,  8b       d8  88   ,adPPYba,   ,adPPYba,  88aaaaaa8P'  88       88  8b,dPPYba,   8b,dPPYba,    ,adPPYba,  8b,dPPYba,  
-#   `"""""8b,  a8P_____88  88P'   "Y8  `8b     d8'  88  a8"     ""  a8P_____88  88""""88'    88       88  88P'   `"8a  88P'   `"8a  a8P_____88  88P'   "Y8  
-#         `8b  8PP"""""""  88           `8b   d8'   88  8b          8PP"""""""  88    `8b    88       88  88       88  88       88  8PP"""""""  88          
-# Y8a     a8P  "8b,   ,aa  88            `8b,d8'    88  "8a,   ,aa  "8b,   ,aa  88     `8b   "8a,   ,a88  88       88  88       88  "8b,   ,aa  88          
-#  "Y88888P"    `"Ybbd8"'  88              "8"      88   `"Ybbd8"'   `"Ybbd8"'  88      `8b   `"YbbdP'Y8  88       88  88       88   `"Ybbd8"'  88          
+
+#  ad88888ba                                        88                          88888888ba
+# d8"     "8b                                       ""                          88      "8b
+# Y8,                                                                           88      ,8P
+# `Y8aaaaa,     ,adPPYba,  8b,dPPYba,  8b       d8  88   ,adPPYba,   ,adPPYba,  88aaaaaa8P'  88       88  8b,dPPYba,   8b,dPPYba,    ,adPPYba,  8b,dPPYba,
+#   `"""""8b,  a8P_____88  88P'   "Y8  `8b     d8'  88  a8"     ""  a8P_____88  88""""88'    88       88  88P'   `"8a  88P'   `"8a  a8P_____88  88P'   "Y8
+#         `8b  8PP"""""""  88           `8b   d8'   88  8b          8PP"""""""  88    `8b    88       88  88       88  88       88  8PP"""""""  88
+# Y8a     a8P  "8b,   ,aa  88            `8b,d8'    88  "8a,   ,aa  "8b,   ,aa  88     `8b   "8a,   ,a88  88       88  88       88  "8b,   ,aa  88
+#  "Y88888P"    `"Ybbd8"'  88              "8"      88   `"Ybbd8"'   `"Ybbd8"'  88      `8b   `"YbbdP'Y8  88       88  88       88   `"Ybbd8"'  88
 
 
 #------------------------------------------------------------------------------------
@@ -15,7 +15,6 @@
 
 set -o nounset
 MYDIR=$( dirname "$(readlink -f "$0")" )
-source "$MYDIR/variables.sh"
 source "$MYDIR/utils.sh"
 
 #------------------------------------------------------------------------------------
@@ -26,17 +25,17 @@ cat <<EOF >&2
 
 NAME
    ${SERVICENAME}
-       
+
 SYNOPSIS
    ${CODE_S}${SERVICENAME} help${CODE_E}
       This help.
-   
+
    ${CODE_S}${SERVICENAME} run${CODE_E}
       Say hello to the world.
-   
+
 DESCRIPTION
    A simple dRunner example. Built from ${IMAGENAME}.
-   
+
 EOF
 }
 
@@ -54,65 +53,42 @@ function dockerrun {
 # The main function. We can add any commands we'd like here!
 
 function main {
-   if [ "$#" -eq 0 ]; then 
+   if [ "$#" -eq 0 ]; then
       die "servicerunner must have the install argument."
    fi
 
-   COMMAND="${1}" 
-   case "$COMMAND" in 
-   
+   COMMAND="${1}"
+   case "$COMMAND" in
+
           #--- standard (required) commands
-   
-         install)
-            ;;
-            
-         obliterate)
-            ;;
-                     
-         uninstall)
-            ;;
-                     
-         backupstart)
-            BACKUPPATH="$2"
-            ;;
-         
-         backupend)
-            BACKUPPATH="$2"
-            ;;
-         
-         restore)
-            RESTOREPATH="$2"
-            ;;
-         
+
          help)
             showhelp
             ;;
-         
+
          enter)
             shift
             dockerrun /bin/bash "$@"
             ;;
-         
-         updatestart)
-            ;;
 
-         updateend)
-            ;;
-         
          selftest)
             ;;
-            
+
          #--- custom commands
 
          run)
             dockerrun helloworld "${SERVICENAME}" "${IMAGENAME}"
             ;;
-            
+
          #--- unrecognised commands
 
          *)
+            # For the standard hooks we don't implement we're required to produce
+            # no output and set exit code 127 (E_NOTIMPL).
+            ! isHook ${COMMAND} || exit 127
+
             showhelp
-            die "Unrecognised command ${CODE_S}${COMMAND}${CODE_E}"            
+            die "Unrecognised command ${CODE_S}${COMMAND}${CODE_E}"
             ;;
    esac
 }
